### ISSUE TITLE
"LoginRadius object has no attribute 'access'" when token has expired

### ISSUE THREAD

**Issue by johnc44** [LoginRadius/python-sdk#2] opened 2019-04-08 08:59 UTC
Login, then call tokenInvalidate.  Then use the API to query a use'rs profile by token and an error is thrown when trying to raise the TokenExpired error.

Code I'm running:

profile = lr.authentication.profile.getByToken(token)

Traceback from exception:

File "/var/task/LoginRadius/__init__.py", line 521, in _process_result\n return self._process_error(result)\n File "/var/task/LoginRadius/__init__.py", line 540, in _process_error\n raise Exceptions.TokenExpired(self.access.expire)\nAttributeError: \'LoginRadius\' object has no attribute \'access\''

**Comment by Karl-LoginRadius** [comment] 2019-04-09 16:14
Thanks for raising this concern, we will review and schedule a fix with our next SDK release. If you need assistance with the current version and handling these exceptions please reach out to LoginRadius support.

**Comment by Sudhanshu-Dubey14** [comment] 2020-10-03 14:44
Hey,
Looks like this issue is not resolved yet.
Can I take this up?

**Comment by ashish8947** [comment] 2020-10-06 05:01
Hello, @Sudhanshu-Dubey14  Thanks for your interest. Please feel free to raise PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by Sudhanshu-Dubey14** [comment] 2020-10-14 07:20
Hey @ashish8947 ,
A bit late I know but I was trying out the demo Flask server provided with the SDK and I have some doubts.
What is the best way to contact the LoginRadius dev community or you?

Thanks and Regards

**Comment by ashish8947** [comment] 2020-10-16 09:36
@Sudhanshu-Dubey14 
Please signup for our [LoginRadius dashboard](https://accounts.loginradius.com/auth.aspx?return_url=https://adminconsole.loginradius.com/login&action=register) and reach out to us via our support channel

**Comment by Sudhanshu-Dubey14** [comment] 2020-10-17 16:43
Hey @ashish8947 ,
Thanks, I have created a ticket (#386) on the Support system.

**Comment by Sudhanshu-Dubey14** [comment] 2020-10-26 05:41
Hey, so I was finally able to login properly into the demo thanks to the support team.
And actually, this particular issue has been already resolved because:

1. The actual code the OP was using (`profile = lr.authentication.profile.getByToken(token)`) is outdated now. The `profile` attribute does not exist anymore as told by this error:

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    profile = loginradius.authentication.profile.getByToken(access_token)
AttributeError: 'AuthenticationApi' object has no attribute 'profile'
```

1. The OP says that "an error is thrown when trying to raise the TokenExpired error" but this is not the case anymore as after invalidating the token using `auth_in_validate_access_token` I tried to `get_access_token_info` and `get_profile_by_access_token` but both of them raised proper TokenExpired info:

```
{'Description': 'The LoginRadius access token has expired, please request a new token from LoginRadius API.', 'ErrorCode': 906, 'Message': 'Access token has expired', 'IsProviderError': False, 'ProviderErrorResponse': None}
{'Description': 'The LoginRadius access token has expired, please request a new token from LoginRadius API.', 'ErrorCode': 906, 'Message': 'Access token has expired', 'IsProviderError': False, 'ProviderErrorResponse': None}
```

So to conclude, this issue was resolved by the development team and it should be closed now.
But while I was exploring this repo I found another issue #36 and raised a PR #37 to fix it but it was labelled "ineligible" for some reason.

**Comment by giriraj12000** [comment] 2021-04-27 11:30
Hi,

As confirmed the issue has been resolved so closing this issue

Thanks

**Closed by giriraj12000** 2021-04-27 11:30 UTC
