### ISSUE TITLE
Incorrect error raised when API Key is missing

### ISSUE THREAD

**Issue by johnc44** [LoginRadius/python-sdk#1] opened 2019-03-25 11:41 UTC
If I create an instance of the LoginRadius class like this:

```
from LoginRadius import LoginRadius as LR
lr = LR()
```

Then I get an error: TypeError: __init__() missing 1 required positional argument: 'version'

This looks to be because the LoginRadius __init__.py is creating a "NoAPIKey" error without passing in the version into its init method.

Full traceback:

```
  File "/var/task/LoginRadius/__init__.py", line 70, in __init__
    raise Exceptions.NoAPIKey
TypeError: __init__() missing 1 required positional argument: 'version'
```

**Comment by Karl-LoginRadius** [comment] 2019-04-09 16:13
Thanks for raising this concern, we will review and schedule a fix with our next SDK release. If you need assistance with the current version and handling these exceptions please reach out to LoginRadius support.

**Comment by divyhshah** [comment] 2020-10-02 16:55
Hey can i take this issue?

**Comment by ashish8947** [comment] 2020-10-06 05:03
Hello, @divyhshah  Thanks for your interest. Please feel free to raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by fumblehool** [comment] 2020-10-14 08:20
@ashish8947 Can I work on it, if thats ok?

**Comment by sushrut111** [comment] 2020-10-18 08:55
I do not see any pull request created for this, can I go ahead and work on this?

**Comment by sushrut111** [comment] 2020-10-18 09:29
This is issue does not seem to be reproducible.

**Comment by Sudhanshu-Dubey14** [comment] 2020-10-26 05:45
Right, this issue does not exist anymore and so it should be closed.

**Comment by giriraj12000** [comment] 2021-04-27 11:39
Hi,

We are unable to replicate the issue and seems the issue is invalid so closing this thread

Thanks

**Closed by giriraj12000** 2021-04-27 11:39 UTC
